#!/bin/sh

PID="org.webosinternals.keyboss"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the keyboss executable
rm -f /var/usr/sbin/${PID}

# Stop the service if running
/sbin/stop ${PID} || true
/usr/bin/killall -9 ${PID} || true

# Remove the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID} /var/palm/event.d/${PID}-settings

# Remove the udev rules file
rm -f /etc/udev/rules.d/49-${PID}.rules

# Install the keyboss executable
mkdir -p /var/usr/sbin/
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${PID} /var/usr/sbin/${PID}

# Install the upstart script
if [ -d /var/palm/event.d ] ; then
  cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /var/palm/event.d/${PID}
else
  cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /etc/event.d/${PID}
fi

# Install the udev rules file
cp $APPS/usr/palm/applications/${PID}/udev/49-${PID}.rules /etc/udev/rules.d/

# Start the service
/sbin/start ${PID}

# Check the upstart script is installed
[ -f /var/palm/event.d/${PID} ] || [ -f /etc/event.d/${PID} ] || exit 1

exit 0

