#!/bin/sh

PID="org.webosinternals.keyboss"
UINPUT="org.webosinternals.modules.uinput"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the keyboss executable
rm -f /var/usr/sbin/${PID}

# Stop the service if running
/sbin/stop ${PID} || true
/usr/bin/killall -9 ${PID} || true

# Remove the dummy uinput upstart script
if [ -f /var/palm/event.d/${UINPUT} ]; then
  grep "Dummy Script" /var/palm/event.d/${UINPUT} && rm -f /var/palm/event.d/${UINPUT}
fi

if [ -f /etc/event.d/${UINPUT} ]; then
  grep "Dummy Script" /etc/event.d/${UINPUT} && rm -f /etc/event.d/${UINPUT}
fi

# Remove the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID} /var/palm/event.d/${PID}-settings

# Remove the udev rules file
rm -f /etc/udev/rules.d/49-${PID}.rules

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/pub/${PID}.json
rm -f /var/palm/ls2/roles/prv/${PID}.json

# Install the keyboss executable
mkdir -p /var/usr/sbin/
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${PID} /var/usr/sbin/${PID}

# Install the upstart script
if [ -d /var/palm/event.d ] ; then
  cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /var/palm/event.d/${PID}
  uinput_file=/var/palm/event.d/${UINPUT}
else
  cp $APPS/usr/palm/applications/${PID}/upstart/${PID} /etc/event.d/${PID}
  uinput_file=/etc/event.d/${UINPUT}
fi

# Install the dummy uinput upstart script
if [ ! -f ${uinput_file} ]; then
  touch ${uinput_file}
  echo "#!/bin/sh" >> ${uinput_file}
  echo "description \"Dummy Script\"" >> ${uinput_file}
  echo "start on stopped finish" >> ${uinput_file}
fi

# Install the udev rules file
cp $APPS/usr/palm/applications/${PID}/udev/49-${PID}.rules /etc/udev/rules.d/

# Install the ls2 roles
cp $APPS/usr/palm/applications/${PID}/ls2/${SID}.json /var/palm/ls2/roles/prv/${PID}.json
cp $APPS/usr/palm/applications/${PID}/ls2/${SID}.json /var/palm/ls2/roles/pub/${PID}.json

# Start the service
/sbin/start ${PID}

# Check the upstart script is installed
[ -f /var/palm/event.d/${PID} ] || [ -f /etc/event.d/${PID} ] || exit 1

exit 0

