#!/bin/sh

SID="org.webosinternals.keyboss"

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the service executable
rm -f /var/usr/sbin/${SID}

# Remove the restart hidd script
rm -f /var/usr/sbin/restart_hidd

# Remove the dbus service
rm -f /var/palm/system-ervices/${SID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/pub/${SID}.json
rm -f /var/palm/ls2/roles/prv/${SID}.json

# Stop the service if running
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${SID}

# Remove the udev rules file
rm -f /etc/udev/rules.d/49-${SID}.rules

exit 0
