#!/bin/sh

PID="org.webosinternals.keyboss"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service if running
/sbin/stop ${PID} || true
/usr/bin/killall -9 ${PID} || true

# Remove the keyboss executable
rm -f /var/usr/sbin/${PID}

# Remove the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID} /var/palm/event.d/${PID}-settings

# Remove the dummy uinput upstart script
if [ -f /var/palm/event.d/${UINPUT} ]; then
  grep "Dummy Script" /var/palm/event.d/${UINPUT} && rm -f /var/palm/event.d/${UINPUT}
fi

if [ -f /etc/event.d/${UINPUT} ]; then
  grep "Dummy Script" /etc/event.d/${UINPUT} && rm -f /etc/event.d/${UINPUT}
fi

# Remove the udev rules file
rm -f /etc/udev/rules.d/49-${PID}.rules

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/pub/${PID}.json
rm -f /var/palm/ls2/roles/prv/${PID}.json
exit 0
